### ISSUE TITLE
Cancelling a build can leave the lockfile, causing subsequent builds to hang until the lockfile is removed manually

### ISSUE THREAD

**Issue by LinusCenterstrom** [MultinetInteractive/MN.L10n#11]
Not sure how to fix this, is there a hook for build cancel?

**Comment by itssimple** [comment]
I have no clue, maybe.

**Comment by itssimple** [comment]
I'll add a timer for it, so if the build takes longer than 10 seconds (default, and other values from eventual config), it should delete the file and retry
