### ISSUE TITLE
Better error message when passing an invalid parameter as the second argument to _s

### ISSUE THREAD

**Issue by LinusCenterstrom** [MultinetInteractive/MN.L10n#17]
If you pass a string for example (instead of an object) it throws a Parameter count mismatch error when it tries to find the properties with reflection.  maybe just try catch internally and throw a better error?

**Comment by itssimple** [comment]
With version 1.0.2 of `MN.L10n.Analyzer` (or the VSIX), you should get errors if you send anything else than an anonymous object or a class to it.
