### ISSUE TITLE
Add sources to phrases.json

### ISSUE THREAD

**Issue by LinusCenterstrom** [MultinetInteractive/MN.L10n#5]
Filenames if there are few usages and extensions if there are many.
Useful for finding phrases that are rarely used and replacing them with other versions.

Could also be useful if we want to generate a subset of the phrases in certain situations.
For example the javascripthandler could return only the phrases that are used in certain filetypes.

Example structure

"Aktiverade": {
   "Created": "2017-11-14T10:50:22.7415827Z",
   "Usages": 1,
   "Comment": null,
   "Sources": ["views/activator.cshtml"]
}

"Artiklar": {
   "Created": "2017-11-14T10:50:22.7415827Z",
   "Usages": 19,
   "Comment": null,
   "Sources": " [".aspx", ".js", ".ts", ".cshtml"]
 }

**Comment by itssimple** [comment]
Fixed in 1.0.115
